### ISSUE TITLE
Test CAMI docker deploy on SNG Gateway

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#208]
## Why
The SNG Gateway needs to be able to host the services that make up the local CAMI Gateway. 
Storage, RabbitMQ broker and Health Measurement services need to be tested to ensure they can be accessed locally.

## What
  - [x] create a new docker-compose file which only deploys these services
  - [x] follow [deploy documentation](https://github.com/cami-project/cami-project/blob/master/README.md) to deploy CAMI services and test access

**Comment by asorici** [comment]
@nikooo777 please close this issue when you are done testing.
If the permissions problem for the RabbitMQ container still persists, open a follow-up describing the error such that we can investigate on our end.
Thank you!

**Comment by nikooo777** [comment]
@asorici I'll close it as soon as I'm done testing.
Thanks

**Comment by nikooo777** [comment]
alright tested the issue i was reporting, seems to be fixed as long as the whole process is run user level rather than as root.
I had to add myself to the docker group through ie. `usermod -aG docker niko` and reboot the system, but it works.

Currently our docker compose looks like this
```
version: '2'
services:
  cami-mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      # Make the MySQL server available on the host so VMs can access it
      - "3307:3306"
  
  cami-store:
    build:
      context: .
      dockerfile: Dockerfile-store
    links:
      - cami-mysql
      - cami-rabbitmq
    ports:
      - "8008:8008"
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-entrypoint.sh

  cami-store-migrate:
    build:
      context: .
      dockerfile: Dockerfile-store
    links:
      - cami-mysql
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-migration-entrypoint.sh

  # Runs the Celery worker for consuming messages received by the store
  cami-store-message-worker:
    build:
      context: .
      dockerfile: Dockerfile-store
    links:
      - cami-mysql
      - cami-rabbitmq
    volumes:
      - .:/cami-project
    entrypoint: ./docker/lib/wait-for-it/wait-for-it.sh -s -t 30 cami-mysql:3306 -- docker-message-worker-entrypoint-dev.sh
  cami-rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    ports:
      # Make the RabbitMQ server available on the host so VMs can access it
      - "5673:5672"
      - "15673:15672"
```

Closing it
